2025-06-13 10:29:06,924 - INFO - üìÅ Reading masterdata.xlsx...
2025-06-13 10:29:07,911 - INFO - üìäÔ∏è Data Processing...
2025-06-13 10:29:10,649 - INFO - üè¢ Processing Department: Altek Medical/DL ACS
2025-06-13 10:29:10,651 - ERROR - ‚ùå An error occurred while executing the programÔºÅ
2025-06-13 10:29:10,653 - ERROR - Traceback (most recent call last):
  File "C:\Users\ythsi\Pycharm\AttendanceProject\main.py", line 374, in <module>
    shutil.copy(EMPLOYEE_TEMPLATE_PATH, DEPARTMENT_OUTPUT_PATH)
  File "C:\Users\ythsi\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 423, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\ythsi\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'output\\June_Altek Medical/DL ACS_Report.xlsx'

